FROM devbook

RUN apt-get update && apt-get install -y \
  ca-certificates \
  curl

# Install Nodejs 16.4.0
ENV NODE_VERSION=16.4.0
ENV NODE_PACKAGE=node-v$NODE_VERSION-linux-x64
ENV NODE_HOME=/opt/$NODE_PACKAGE

ENV NODE_PATH $NODE_HOME/lib/node_modules
ENV PATH $NODE_HOME/bin:$PATH

RUN curl https://nodejs.org/dist/v$NODE_VERSION/$NODE_PACKAGE.tar.gz | tar -xzC /opt/

# Install Banana Node API as a global package.

RUN npm i -g @banana-dev/banana-dev
